---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    apt: name=tomcat9 state=present
  - name: start tomcat9
    service: name=tomcat9 state=started
  - name: deploy war file
    get_url:
     url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
     dest=/usr/share/tomcat9/webapps
    notify: restart tomcat9
  handlers:
   - name: restart tomcat9
     service: name=tomcat9 state=restarted
