---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: upgrade packgs
    apt: name=* state=latest update_cache=yes
  - name: install apache2
    apt: name=httpd state=present
  - name: start httpd
    service: name=httpd state=started
  - name: deploy html file
    copy: src=demohttpd.html dest=/var/www/html
    notify: restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
