---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: upgrade packgs
    apt: name=* state=latest update_cache=yes
  - name: install apache2
    apt: name=apache2 state=present
  - name: start apache2
    service: name=apache2 state=started
  - name: deploy html file
    copy: src=demohttpd.html dest=/var/www/html
    notify: restart apache2
  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted
